# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: graja <graja@student.42wolfsburg.de>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/10 15:54:02 by graja             #+#    #+#              #
#    Updated: 2021/12/10 16:03:37 by graja            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= megaphone
SRC	= megaphone.cpp
FLAGS	= -Wall -Wextra -Werror
CC	= c++

$(NAME)		:	$(SRC)
	$(CC) $(FLAGS) $(SRC) -o $(NAME)

all		:	$(NAME)

clean		:

fclean		:
	rm -f $(NAME)

re		:	fclean all

